### ISSUE TITLE
Title: Adding basic problems based on recursion 

### ISSUE THREAD

**Issue by navyaajainnn** [Kushal997-das/SkillShow#113]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your proposal related to a problem? Please describe.

Recursion is a crucial topic to be mastered in DSA. It is useful in dynamic programming as well as other problems that revolves around continuously breaking down one big problem into smaller simple problems and solving them. I want to add few questions of recursion

**Comment by Ghanshyam-07** [comment]
@Kushal997-das  please assign it to me , I will add a recursion question along with its solution that will help in understanding recursion
