### ISSUE TITLE
Title: Add "Find the Shortest Path in a Weighted Graph" question

### ISSUE THREAD

**Issue by leotran20** [Kushal997-das/SkillShow#21]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like.

Find the Shortest Path in a Weighted Graph

You are given a weighted graph with 5 nodes (A, B, C, D, E) and the following edges:

| From | To | Weight |
|------|----|--------|
| A    | B  | 4      |
| A    | C  | 2      |
| B    | C  | 1      |
| B    | D  | 5      |
| C    | D  | 3      |
| C    | E  | 2      |
| D    | E  | 1      |

Find the shortest path from node A to node E using Dijkstra's algorithm.

**Requirements:**
1. Implement Dijkstra's algorithm in Python.
2. Use a priority queue to efficiently select the next node.
3. Return the shortest path and its total weight.

**Output:**
```
Shortest path: A -> C -> E
Total weight: 4
```

**Comment by g76728443** [comment]
I can solve this issue. @Kushal997-das, please assign it to me
