### ISSUE TITLE
Title: Add a Beginner level Question and Solution on Arrays

### ISSUE THREAD

**Issue by kumar007ambi** [Kushal997-das/SkillShow#25]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

Yes

### Describe the solution you'd like.

Question : Reverse array in groups
Description : Given an array arr of positive integers. Reverse every sub-array group of size k.
I will Provide solution in C

**Comment by Kirti-Pant** [comment]
hey, @Kushal997-das  can you assign me this issue??
