### ISSUE TITLE
Title: Added Random Fun Fact Generator task 

### ISSUE THREAD

**Issue by AhmedFaizanDev** [Kushal997-das/SkillShow#26]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

Yes

### Describe the solution you'd like.

I want to add a beginner task titled "Random Fun Fact Generator". This task involves creating a Python program that displays a random fun fact from a pre-defined list. It includes a question.md file and a fun_facts.py file with the solution.

**Comment by g76728443** [comment]
I can solve this issue. @Kushal997-das, please assign it to me

**Comment by AhmedFaizanDev** [comment]
Please can I work on this ?
