### ISSUE TITLE
Python program that displays a random fun fact

### ISSUE THREAD

**Issue by AhmedFaizanDev** [Kushal997-das/SkillShow#52]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your feature request related to a problem? Please describe.

Write a Python program that displays a random fun fact each time it's executed

### Describe the solution you'd like.

- Use a list of at least 5 fun facts.
- Randomly select and display one fact from the list.
- The program should run in Python.

**Comment by g76728443** [comment]
I can solve this issue. @Kushal997-das, please assign it to me
