### ISSUE TITLE
Title: To add upper bound problem of binary search in python

### ISSUE THREAD

**Issue by Aishwarya-S-Sharma** [Kushal997-das/SkillShow#68]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Is your proposal related to a problem? Please describe.

To add clear and concise code

**Comment by Aishwarya-S-Sharma** [comment]
@Kushal997-das  assign this to me please

**Comment by Kushal997-das** [comment]
Don’t spam here by creating multiple issues at a time. I already mentioned it now let me close all your issues
