### ISSUE TITLE
Maximum Swap

### ISSUE THREAD

**Issue by Ghanshyam-07** [Kushal997-das/SkillShow#83]
### Initiative (Required)

Hacktoberfest 2024 🎃

### Additional Info

I have added a new problem titled "Maximum Swap" along with its solution. The problem involves finding the maximum number  by swapping at most two digit, utilizing Greedy Algorithm to optimize the solution. I request you to add it to the repository, followed all the guidelines and filled data.json too correctly.

**Comment by g76728443** [comment]
I want to work on it, @Kushal997-das please assign it to me.
